### ISSUE TITLE
[Epic] Update transaction follow ups

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1589]
Follow ups to #1558

TODO:

* [ ] Expose a Python API that accepts Python values instead of SQL strings.
* [ ] Support updated nested fields
* [ ] Support distributed execution of update query
* [ ] Pass through write parameters
* [ ] Profile and introduce parallelism
* [ ] Auto-compaction
* [ ] Index re-mapping

**Comment by zeddit** [comment]
`update` or `merge_insert` will mess up the order of rows of the origin table, it put the newly changed rows at the bottom of the table, which would be bad for time series tables where rows are firstly inserted in order.

and it's hard for people to read the whole dataset and reorder them outside the lance because of the dataset scale.

For iceberg table, it has `sorted table` where data files are guaranteed within a single file and statistics could be useful for hinting merge.

would lance support the sort-order? great thanks.

**Comment by wjones127** [comment]
> it put the newly changed rows at the bottom of the table, which would be bad for time series tables where rows are firstly inserted in order.

The tough thing here is if we try to preserve order, we have to rewrite all rows. This is because lance files are immutable, so if you want to change one row in the middle of a file but keep order, you just have to copy basically the entire file. Maybe you don't mind that kind of write amplification for your use case, but I don't think we'd want to make that default. So any kind of row preservation needs to be behind a specific user-provided setting.

> it's very happy to see lance won't change order when conducting compaction, and would lance support the sort-order?

I think we could look into it. But it would change pretty much any operation that updates rows. TBH, by default I think we might change compaction to not preserve row order, unless you ask it to.
