### ISSUE TITLE
feat: support drop column api in Dataset

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lance#1674]
# Problem Statament

* We have API (i.e., `Dataset::merge()`) for zero-copy schema evolution (i..e, adding new columns). We need similar function to conduct zero-overhead drop column as well.

## TODO

* [ ] Implement drop column in Rust
* [ ] Expose drop column in Python
* [ ] Add compaction criterion for dropped columns

**Comment by Xuanwo** [comment]
Closing as completed by #1695 and #1904. Metadata-only `drop_columns` is available in Rust and Python. Compaction policy for dropped columns remains a separate follow-up.
