### ISSUE TITLE
Scanner simplification

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1782]
The code in [dataset/scanner.rs](https://github.com/lancedb/lance/blob/74b743aebebd024f4bce76024b260b521fdc45ed/rust/lance/src/dataset/scanner.rs) has gotten extremely complicated, to a point where it is hard to test. Before we make any improvements, we need to refactor this to be easier to test and extend.

## Tasks

* [ ] Create a [LogicalPlan](https://docs.rs/datafusion-expr/latest/datafusion_expr/logical_plan/enum.LogicalPlan.html) for KNN search
* [ ] Write an extension for [LogicalPlanBuilder](https://docs.rs/datafusion-expr/latest/datafusion_expr/logical_plan/builder/struct.LogicalPlanBuilder.html) and rewrite `Scanner::create_plan()` in terms of that.
* [ ] Create a custom [PhysicalPlanner](https://docs.rs/datafusion/latest/datafusion/physical_planner/trait.PhysicalPlanner.html) to convert out logical plans into relevant nodes
* [ ] Implement a [PhysicalOptimizerRule](https://docs.rs/datafusion/latest/datafusion/physical_optimizer/optimizer/trait.PhysicalOptimizerRule.html) for each of the optimizations we make:
   * [ ] Using vector indices (ANN)
   * [ ] Using scalar indices (ANN and scan)

**Comment by jayzhan211** [comment]
I'm interesting in improve datafusion extensibility for lance

**Comment by wjones127** [comment]
I think a good approach to this would be starting to design some logical plan nodes implementing [UserDefinedLogicalNode](https://docs.rs/datafusion-expr/latest/datafusion_expr/logical_plan/trait.UserDefinedLogicalNode.html).

From there, we can create a `create_plan_v2()` method that creates a logical plan instead of the `ExecutionPlan`. Later then we can physical planner and other things. This would keep the existing planning intact until we are ready to switch things over.

> I'm interesting in improve datafusion extensibility for lance

Is there a particular goal you have in mind that you want to work towards?

**Comment by jayzhan211** [comment]
> Is there a particular goal you have in mind that you want to work towards?

None yet. I would like to know how lance built on datafusion and what are the room for improvement

> I think a good approach to this would be starting to design some logical plan nodes implementing [UserDefinedLogicalNode](https://docs.rs/datafusion-expr/latest/datafusion_expr/logical_plan/trait.UserDefinedLogicalNode.html).

Probably I could start from this!

**Comment by wjones127** [comment]
@jayzhan211 If you want a smaller issue to get started with, this might be a better one: https://github.com/lancedb/lance/issues/1927 It will also have a more immediate pay off.

**Comment by Xuanwo** [comment]
Hi @wjones127, I'm interested in this issue and will start working on it soon.

Let me repeat our plan to make sure we're aligned: We will implement our own ANN/KNN search as an extension of Datafusion's `Extension` logical plan. This will allow us to reuse Datafusion's LogicalPlanBuilder. After that, we can implement the executor, planner, and optimizer.

Once these changes are made, we will move from `Scanner → PhysicalPlan` to `Scanner → LogicalPlan → Optimize → PhysicalPlan`.

Did I understand this correctly?

**Comment by westonpace** [comment]
https://github.com/apache/datafusion/discussions/16358 is possibly relatedd

**Comment by wjones127** [comment]
I looked at scanner.rs again and am still unnerved by it. So I spent some time with an LLM brainstorming and came up with some further ideas of how we could refactor this: https://docs.google.com/document/d/1n3RyggZMl6CJMJa7CMz0KDHkyFIZw2RGo8PQnIkRdZQ/edit?usp=sharing

I don't expect to pick this up any time soon, but just wanted to park the ideas here in case they are helpful.
