### ISSUE TITLE
[EPIC] bfloat16 support

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#1813]
* [x] #1684
* [ ] #1751
* [ ] #778
* [ ] #1814
* [ ] #1651 
* [ ] Write a blog post about bf16 support in Lance
* [ ] In LanceDB, support easily creating bf16 in schemas
* [ ] In Lance and LanceDB, have tutorial for migrating from a f32 to bf16 vector column (using add_columns) API.
  * [x] https://github.com/lancedb/lance/issues/1458
