### ISSUE TITLE
Make filter happen before k in ANN queries

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance#955]
Right now, when we make an NN query (ANN or flat) it will get the top `k` *and then* perform the filter. It would be much more useful if we got the top `k` after filters. However, without more work on improving indexing and fragment-level stats, this will have high latency in many cases.

## Indexes

For IVF+PQ, we could include a selection of metadata columns within the index. Then we could filter on those columns at the same time as we read the index, making the IO for executing filters much more efficient.

For both IVF+PQ and DiskANN, we can use fragment-level partition and statistics information to prune the rowids based on which fragments they belong to.

## Tasks

* [ ] Complete implementation of filter before k (prototyped in #971).
* [ ] Use partition values with filters in ANN queries
* [ ] Use file-level stats with filters in ANN queries
* [ ] Support including metadata columns inside the IVF+PQ index.
* [ ] Add a timeout in the refine step, so even if filters take a long time we only wait a fixed amount of time.
* [ ] Add caching after the refine step, so that subsequent paginated queries are very fast.

**Comment by wjones127** [comment]
Add a timeout so that it doesn't take unbounded time to return filtered results.

**Comment by wjones127** [comment]
Superseded by scalar index + pre-filtering approach.
